# Generated by Django 3.2.21 on 2023-10-20 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
