# Generated by Django 3.2.21 on 2023-10-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
